# Generated by Django 4.1.5 on 2023-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appimage',
            name='isPrime',
        ),
        migrations.AddField(
            model_name='app',
            name='poster',
            field=models.FileField(null=True, upload_to='app_poster/'),
        ),
    ]
